import type { ColumnRegular } from '@revolist/revogrid';
import { createDefaultTaskTableColumn, type AssignmentEntity, type BaselineSnapshot, type CalendarEntity, type DependencyEntity, type GanttPluginConfig, type GanttTaskSourceRow, type ResourceEntity } from '@revolist/gantt';
import { resolveIndustryWorkflowStatus, type IndustryGanttDefinition } from '../shared/industry-use-case.types';

type ErpTaskRow = GanttTaskSourceRow & {
  statusLabel: string;
  orderNumber?: string;
  customer?: string;
  site?: string;
  workCenter?: string;
  machine?: string;
  material?: string;
  risk?: string;
};

const CALENDAR_ID = 'erp-standard';
const taskDefaults = { customer: 'Northwind Energy', site: 'Porto · Plant 04', calendarId: CALENDAR_ID, tags: [] as readonly string[] };
const task = (row: Omit<ErpTaskRow, 'customer' | 'site' | 'calendarId' | 'tags'> & Partial<Pick<ErpTaskRow, 'customer' | 'site' | 'calendarId' | 'tags'>>): ErpTaskRow => ({ ...taskDefaults, ...row } as ErpTaskRow);

export const ERP_TASK_IDS = ['erp-release', 'wo-8041', 'wo-8041-materials', 'wo-8041-machine', 'wo-8041-coating', 'wo-8041-assembly', 'wo-8041-quality', 'wo-8042', 'wo-8042-kit', 'wo-8042-cabinet', 'wo-8042-wiring', 'wo-8042-firmware', 'wo-8042-fat', 'wo-8042-release', 'delivery', 'delivery-pack', 'delivery-docs', 'delivery-dock', 'delivery-customer'] as const;

export const ERP_TASKS: ErpTaskRow[] = [
  task({ id: 'erp-release', parentId: null, type: 'summary', name: 'August production release', orderNumber: 'REL-0826', workCenter: 'Production control', statusLabel: 'At risk', workflowStatus: 'blocked', startDate: '2026-08-10', endDate: '2026-09-30', duration: 38, percentDone: 48, risk: 'Coating supplier approval' }),
  task({ id: 'wo-8041', parentId: 'erp-release', type: 'summary', name: 'Servo pump assembly · 24 units', orderNumber: 'WO-8041', workCenter: 'Line A', statusLabel: 'At risk', workflowStatus: 'blocked', startDate: '2026-08-10', endDate: '2026-09-10', duration: 24, percentDone: 61, risk: 'Coating supplier approval' }),
  task({ id: 'wo-8041-materials', parentId: 'wo-8041', type: 'task', name: 'Release bearing and seal kits', orderNumber: 'WO-8041', workCenter: 'Stores', machine: 'ASRS-02', material: 'KIT-SP24', statusLabel: 'Complete', workflowStatus: 'done', startDate: '2026-08-10', endDate: '2026-08-14', duration: 5, percentDone: 100 }),
  task({ id: 'wo-8041-machine', parentId: 'wo-8041', type: 'task', name: 'Machine pump housings', orderNumber: 'WO-8041', workCenter: 'CNC cell', machine: 'CNC-07', material: 'AL-6061', statusLabel: 'Running', workflowStatus: 'in-progress', startDate: '2026-08-17', endDate: '2026-08-24', duration: 6, percentDone: 82 }),
  task({ id: 'wo-8041-coating', parentId: 'wo-8041', type: 'task', name: 'Coating batch approval', orderNumber: 'WO-8041', workCenter: 'Supplier', machine: 'Vendor line', material: 'CT-441', statusLabel: 'Blocked', workflowStatus: 'blocked', startDate: '2026-08-25', endDate: '2026-09-02', duration: 7, percentDone: 20, deadlineDate: '2026-08-31', risk: 'Supplier certificate overdue' }),
  task({ id: 'wo-8041-assembly', parentId: 'wo-8041', type: 'task', name: 'Final assembly and torque', orderNumber: 'WO-8041', workCenter: 'Line A', machine: 'ASM-03', material: 'SP-2400', statusLabel: 'Queued', workflowStatus: 'not-started', startDate: '2026-09-03', endDate: '2026-09-08', duration: 4, percentDone: 0 }),
  task({ id: 'wo-8041-quality', parentId: 'wo-8041', type: 'milestone', name: 'Pump batch released', orderNumber: 'WO-8041', workCenter: 'Quality', statusLabel: 'Gate', workflowStatus: 'not-started', startDate: '2026-09-10', endDate: '2026-09-10', duration: 0, percentDone: 0 }),
  task({ id: 'wo-8042', parentId: 'erp-release', type: 'summary', name: 'Control cabinet batch · 12 units', orderNumber: 'WO-8042', workCenter: 'Electrical', statusLabel: 'On schedule', workflowStatus: 'in-progress', startDate: '2026-08-12', endDate: '2026-09-18', duration: 28, percentDone: 44 }),
  task({ id: 'wo-8042-kit', parentId: 'wo-8042', type: 'task', name: 'Stage cabinet component kits', orderNumber: 'WO-8042', workCenter: 'Stores', machine: 'ASRS-01', material: 'KIT-CC12', statusLabel: 'Complete', workflowStatus: 'done', startDate: '2026-08-12', endDate: '2026-08-18', duration: 5, percentDone: 100 }),
  task({ id: 'wo-8042-cabinet', parentId: 'wo-8042', type: 'task', name: 'Fabricate cabinet enclosures', orderNumber: 'WO-8042', workCenter: 'Fabrication', machine: 'LASER-04', material: 'SS-304', statusLabel: 'Running', workflowStatus: 'in-progress', startDate: '2026-08-19', endDate: '2026-08-27', duration: 7, percentDone: 64 }),
  task({ id: 'wo-8042-wiring', parentId: 'wo-8042', type: 'task', name: 'Panel wiring and inspection', orderNumber: 'WO-8042', workCenter: 'Electrical', machine: 'BENCH-12', material: 'HARNESS-C12', statusLabel: 'Ready', workflowStatus: 'not-started', startDate: '2026-08-28', endDate: '2026-09-08', duration: 8, percentDone: 0 }),
  task({ id: 'wo-8042-firmware', parentId: 'wo-8042', type: 'task', name: 'Load PLC firmware', orderNumber: 'WO-8042', workCenter: 'Controls', machine: 'TEST-05', material: 'FW-6.4', statusLabel: 'Ready', workflowStatus: 'not-started', startDate: '2026-09-07', endDate: '2026-09-11', duration: 5, percentDone: 0 }),
  task({ id: 'wo-8042-fat', parentId: 'wo-8042', type: 'task', name: 'Factory acceptance test', orderNumber: 'WO-8042', workCenter: 'Test bay', machine: 'FAT-02', material: 'CC-1200', statusLabel: 'Planned', workflowStatus: 'not-started', startDate: '2026-09-14', endDate: '2026-09-16', duration: 3, percentDone: 0 }),
  task({ id: 'wo-8042-release', parentId: 'wo-8042', type: 'milestone', name: 'Cabinet batch released', orderNumber: 'WO-8042', workCenter: 'Quality', statusLabel: 'Gate', workflowStatus: 'not-started', startDate: '2026-09-18', endDate: '2026-09-18', duration: 0, percentDone: 0 }),
  task({ id: 'delivery', parentId: 'erp-release', type: 'summary', name: 'Customer delivery', orderNumber: 'SHIP-2638', workCenter: 'Logistics', statusLabel: 'Planned', workflowStatus: 'not-started', startDate: '2026-09-21', endDate: '2026-09-30', duration: 8, percentDone: 0 }),
  task({ id: 'delivery-pack', parentId: 'delivery', type: 'task', name: 'Consolidate and export-pack', orderNumber: 'SHIP-2638', workCenter: 'Dispatch', machine: 'DOCK-03', material: 'CRATE-ISPM15', statusLabel: 'Planned', workflowStatus: 'not-started', startDate: '2026-09-21', endDate: '2026-09-23', duration: 3, percentDone: 0 }),
  task({ id: 'delivery-docs', parentId: 'delivery', type: 'task', name: 'Compile compliance dossier', orderNumber: 'SHIP-2638', workCenter: 'Quality', material: 'DOC-MDR', statusLabel: 'Planned', workflowStatus: 'not-started', startDate: '2026-09-21', endDate: '2026-09-24', duration: 4, percentDone: 0 }),
  task({ id: 'delivery-dock', parentId: 'delivery', type: 'milestone', name: 'Carrier dock appointment', orderNumber: 'SHIP-2638', workCenter: 'Dispatch', statusLabel: 'Booked', workflowStatus: 'not-started', startDate: '2026-09-25', endDate: '2026-09-25', duration: 0, percentDone: 0 }),
  task({ id: 'delivery-customer', parentId: 'delivery', type: 'milestone', name: 'Northwind site delivery', orderNumber: 'SHIP-2638', workCenter: 'Customer site', statusLabel: 'Committed', workflowStatus: 'not-started', startDate: '2026-09-30', endDate: '2026-09-30', duration: 0, percentDone: 0 }),
];

export const ERP_CALENDARS: CalendarEntity[] = [{ id: CALENDAR_ID, name: 'Porto two-shift calendar', timeZone: 'Europe/Lisbon', workingDays: [1, 2, 3, 4, 5], workingHours: [{ start: '06:00', end: '14:00' }, { start: '14:00', end: '22:00' }], holidays: ['2026-08-15'], hoursPerDay: 16 }];
export const ERP_RESOURCES: ResourceEntity[] = [
  ['planner', 'Marta Silva', 'Production planner', 64], ['cnc-team', 'CNC Cell 07', 'Machine cell', 155], ['assembly-team', 'Line A crew', 'Assembly crew', 128], ['electrical-team', 'Electrical team', 'Panel technicians', 116], ['controls', 'Inês Costa', 'Controls engineer', 98], ['quality', 'Rui Gomes', 'Quality lead', 86], ['logistics', 'Joana Reis', 'Logistics coordinator', 72],
].map(([id, name, role, hourlyCost]) => ({ id, name, role, calendarId: CALENDAR_ID, allocationCapacity: 1, hourlyCost } as ResourceEntity));
const resourceFor = (workCenter: string) => workCenter === 'CNC cell' ? 'cnc-team' : workCenter === 'Line A' ? 'assembly-team' : ['Electrical', 'Fabrication'].includes(workCenter) ? 'electrical-team' : workCenter === 'Controls' ? 'controls' : ['Quality', 'Test bay'].includes(workCenter) ? 'quality' : ['Logistics', 'Dispatch', 'Customer site'].includes(workCenter) ? 'logistics' : 'planner';
export const ERP_ASSIGNMENTS: AssignmentEntity[] = ERP_TASKS.filter(({ type }) => type !== 'summary').map((item, index) => ({ id: `erp-a-${index + 1}`, taskId: item.id, resourceId: resourceFor(item.workCenter), allocationUnits: 1, responsibility: 'Owner' }));
const dependencyPairs = [['wo-8041-materials', 'wo-8041-machine', 'finish-to-start'], ['wo-8041-machine', 'wo-8041-coating', 'finish-to-start'], ['wo-8041-coating', 'wo-8041-assembly', 'finish-to-start'], ['wo-8041-assembly', 'wo-8041-quality', 'finish-to-start'], ['wo-8042-kit', 'wo-8042-cabinet', 'finish-to-start'], ['wo-8042-cabinet', 'wo-8042-wiring', 'finish-to-start'], ['wo-8042-wiring', 'wo-8042-firmware', 'start-to-start'], ['wo-8042-wiring', 'wo-8042-fat', 'finish-to-start'], ['wo-8042-firmware', 'wo-8042-fat', 'finish-to-start'], ['wo-8042-fat', 'wo-8042-release', 'finish-to-start'], ['wo-8041-quality', 'delivery-pack', 'finish-to-start'], ['wo-8042-release', 'delivery-pack', 'finish-to-start'], ['delivery-pack', 'delivery-dock', 'finish-to-start'], ['delivery-docs', 'delivery-dock', 'finish-to-start'], ['delivery-dock', 'delivery-customer', 'finish-to-start']] as const;
export const ERP_DEPENDENCIES: DependencyEntity[] = dependencyPairs.map(([predecessorTaskId, successorTaskId, type], index) => ({ id: `erp-d-${index + 1}`, predecessorTaskId, successorTaskId, type, lagDays: 0 }));

const approvedDates: Record<string, readonly [string, string]> = { 'erp-release': ['2026-08-10', '2026-09-28'], 'wo-8041': ['2026-08-10', '2026-09-07'], 'wo-8041-coating': ['2026-08-25', '2026-08-28'], 'wo-8041-assembly': ['2026-08-31', '2026-09-04'], 'wo-8041-quality': ['2026-09-07', '2026-09-07'], delivery: ['2026-09-18', '2026-09-28'], 'delivery-pack': ['2026-09-18', '2026-09-22'], 'delivery-dock': ['2026-09-23', '2026-09-23'], 'delivery-customer': ['2026-09-28', '2026-09-28'] };
export const ERP_BASELINES: BaselineSnapshot[] = [{ id: 'erp-approved', name: 'Approved August release', capturedAt: '2026-08-07T09:00:00Z', tasks: ERP_TASKS.map((item) => { const [startDate, endDate] = approvedDates[item.id] ?? [item.startDate, item.endDate ?? item.startDate]; return { taskId: item.id, startDate, endDate, duration: item.type === 'milestone' ? 0 : Number(item.duration) * 16, progressPercent: 0 }; }) } as BaselineSnapshot];

const compactStatuses: Record<string, string> = { Complete: 'Done', Running: 'Active', Blocked: 'Hold', 'On schedule': 'On plan', Planned: 'Plan', Committed: 'Commit' };
type ErpCellRole = 'work-order' | 'state';
const erpCellProperties = (role: ErpCellRole) => () => ({ class: { 'erp-grid-cell': true, [`erp-grid-cell--${role}`]: true } });
const statusColumn: ColumnRegular = { prop: 'statusLabel', name: 'State', size: 87, readonly: true, cellProperties: erpCellProperties('state'), cellTemplate: (h, { model }) => h('span', { class: `erp-state erp-state--${model.workflowStatus ?? 'not-started'}`, title: model.statusLabel }, compactStatuses[model.statusLabel] ?? model.statusLabel) };
export const ERP_COLUMNS: ColumnRegular[] = [
  { prop: 'orderNumber', name: 'WO', size: 103, readonly: true, cellProperties: erpCellProperties('work-order'), cellTemplate: (h, { model }) => h('span', { class: 'erp-work-order', title: model.orderNumber }, model.orderNumber) },
  { ...createDefaultTaskTableColumn('name'), name: 'Operation', size: 184 },
  statusColumn,
];
export const ERP_GANTT_CONFIG: GanttPluginConfig = { id: 'erp-production-release-0826', name: 'August production release', version: '1', currency: 'EUR', timeZone: 'Europe/Lisbon', primaryCalendarId: CALENDAR_ID, updatedAt: '2026-08-26T08:42:00Z', statusDate: '2026-08-26', zoomPreset: 'day-week', weekStartsOn: 1, allowTaskCreate: false, scheduling: { excludeHolidaysFromDuration: true, taskModeDefault: 'auto', autoDependencyViolationBehavior: 'warn', lagCalendar: 'working-days', resourceLeveling: 'warn' }, dateFormats: { locale: 'en-GB', timeZone: 'Europe/Lisbon', table: { day: '2-digit', month: 'short' } }, visuals: { showDependencies: true, showBaseline: false, baselineId: 'erp-approved', showCriticalPath: true, showTaskLabels: 'tasks', shadeNonWorkingTime: true, showTodayLine: false, projectLineDate: '2026-08-26', timeRanges: [{ id: 'supplier-window', startDate: '2026-08-25', endDate: '2026-09-02', label: 'Supplier recovery', color: '#fef2f2' }], milestoneLines: [{ id: 'erp-release-gate', date: '2026-09-18', label: 'Release gate', color: '#7c3aed' }, { id: 'customer-commit', date: '2026-09-30', label: 'Delivery', color: '#0f766e' }], taskTooltipFields: ['status', 'startDate', 'endDate', 'percentDone', 'assignees'] } };

export const ERP_INDUSTRY_DEFINITION: IndustryGanttDefinition<ErpTaskRow> = { id: 'industry-erp', productLabel: 'Northwind / ERP / Porto Plant 04', title: 'Production cockpit', subtitle: 'MRP release REL-0826 · live work orders and material constraints', scheduleLabel: 'Work-center plan · Release REL-0826', riskLegendLabel: 'Supplier hold', updatedLabel: 'MRP sync 08:42 · 26 Aug 2026', mark: 'NW', metrics: [{ label: 'Open WOs', value: '2' }, { label: 'Plan attainment', value: '93%', tone: 'positive' }, { label: 'Material holds', value: '1', tone: 'danger' }, { label: 'OTIF commit', value: '30 Sep', tone: 'warning' }], grid: { theme: 'adaptiveCompact', rowSize: 30, rowHeaders: true, cellBorders: true }, tasks: ERP_TASKS, dependencies: ERP_DEPENDENCIES, calendars: ERP_CALENDARS, resources: ERP_RESOURCES, assignments: ERP_ASSIGNMENTS, baselines: ERP_BASELINES, columns: ERP_COLUMNS, gantt: ERP_GANTT_CONFIG, taskBarColorHook: ({ row }) => { const source = row as typeof row & { statusLabel?: string }; const workflowStatus = resolveIndustryWorkflowStatus(row); if (workflowStatus === 'blocked' || source.statusLabel === 'Blocked') return { barColor: '#e36f72', progressColor: '#db4f53', borderColor: '#d65a5e', textColor: '#fff' }; if (workflowStatus === 'done' || source.statusLabel === 'Complete') return { barColor: '#849892', progressColor: '#657a74', borderColor: '#60756f', textColor: '#fff' }; if (row.type !== 'summary' && workflowStatus === 'in-progress') return { barColor: '#abe8ae', progressColor: '#76cb7c', borderColor: '#90d694', textColor: '#17311b' }; return undefined; } };
