import { Component, NO_ERRORS_SCHEMA, ViewEncapsulation } from '@angular/core';
import type { OnDestroy } from '@angular/core';
import { RevoGrid } from '@revolist/angular-datagrid';
import type { GanttPluginConfig } from '@revolist/gantt';
import { currentTheme, observeCurrentTheme } from '../../theme';
import { resolveIndustryGantt } from './industry-use-case.catalog';
import { createIndustryGanttConfig } from './industry-use-case.types';
import { industryGridClass, industryGridTheme, industryPlugins, industryShellClass } from './industry-use-case.shared';

@Component({ selector: 'industry-gantt-grid', standalone: true, imports: [RevoGrid], schemas: [NO_ERRORS_SCHEMA], encapsulation: ViewEncapsulation.None, styleUrls: ['./industry-use-case.scss'], host: { class: 'industry-gantt-angular-host' }, template: `
  <section [class]="shellClass" [attr.aria-label]="definition.productLabel + ' ' + definition.title">
    <header class="industry-gantt-header"><div class="industry-gantt-identity"><span class="industry-gantt-mark">{{ definition.mark }}</span><div><div class="industry-gantt-product">{{ definition.productLabel }}</div><h1 class="industry-gantt-title">{{ definition.title }}</h1><p class="industry-gantt-subtitle">{{ definition.subtitle }}</p></div></div><div class="industry-gantt-metrics">@for(metric of definition.metrics; track metric.label){<div [class]="'industry-gantt-metric industry-gantt-metric--' + (metric.tone ?? 'default')"><strong class="industry-gantt-metric__value">{{ metric.value }}</strong><span class="industry-gantt-metric__label">{{ metric.label }}</span></div>}</div><div class="industry-gantt-sync"><span class="industry-gantt-sync__dot"></span>{{ definition.updatedLabel }}</div></header>
    <div class="industry-gantt-toolbar"><span class="industry-gantt-toolbar__label">{{ definition.scheduleLabel }}</span><span class="industry-gantt-toolbar__legend">{{ definition.riskLegendLabel }}</span><button type="button" class="industry-gantt-toggle" [attr.aria-pressed]="showBaseline" (click)="toggleBaseline()">Baseline</button><button type="button" class="industry-gantt-toggle" [attr.aria-pressed]="showCritical" (click)="toggleCritical()">Critical path</button></div>
    <revo-grid [class]="gridClass" [theme]="theme" [hideAttribution]="true" [readonly]="false" [range]="true" [resize]="true" [rowSize]="definition.grid?.rowSize ?? 34" [rowHeaders]="definition.grid?.rowHeaders ?? false" [autoSizeColumn]="false" [plugins]="plugins" [columns]="columns" [source]="source" [additionalData]="additionalData" [gantt]="gantt" [ganttDependencies]="dependencies" [ganttCalendars]="calendars" [ganttResources]="resources" [ganttAssignments]="assignments" [ganttBaselines]="baselines"></revo-grid>
  </section>` })
export class IndustryGanttGridComponent implements OnDestroy {
  readonly definition = resolveIndustryGantt(window.location.search); readonly plugins = industryPlugins(this.definition); readonly columns = [...this.definition.columns]; readonly source = [...this.definition.tasks]; readonly dependencies = [...this.definition.dependencies]; readonly calendars = [...this.definition.calendars]; readonly resources = [...this.definition.resources]; readonly assignments = [...this.definition.assignments]; readonly baselines = [...this.definition.baselines]; readonly additionalData = { industryUseCase: this.definition.id };
  showBaseline = false; showCritical = true; gantt: GanttPluginConfig = createIndustryGanttConfig(this.definition, false, true); private dark = currentTheme().isDark(); theme = industryGridTheme(this.definition, this.dark); gridClass = industryGridClass(this.definition); shellClass = industryShellClass(this.dark, this.definition.id); private readonly disconnect = observeCurrentTheme((value) => { this.dark = value; this.theme = industryGridTheme(this.definition, value); this.shellClass = industryShellClass(value, this.definition.id); });
  toggleBaseline(){ this.showBaseline = !this.showBaseline; this.refresh(); } toggleCritical(){ this.showCritical = !this.showCritical; this.refresh(); } private refresh(){ this.gantt = createIndustryGanttConfig(this.definition, this.showBaseline, this.showCritical); } ngOnDestroy(){ this.disconnect(); }
}
